//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Class_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class izbor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public izbor()
        {
            this.vasIzborDana = new HashSet<vasIzborDana>();
        }
    
        public int id { get; set; }
        public string predjelo { get; set; }
        public string prilog { get; set; }
        public string meso { get; set; }
        public string desert { get; set; }
        public byte aktivanIzbor { get; set; }
        public int kategorijaId { get; set; }
    
        public virtual izborKategorija izborKategorija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vasIzborDana> vasIzborDana { get; set; }
    }
}
