//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Class_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public korisnik()
        {
            this.korisnikLijeka = new HashSet<korisnikLijeka>();
            this.nalaz = new HashSet<nalaz>();
            this.podsjetnik = new HashSet<podsjetnik>();
            this.rezervacijaPraonice = new HashSet<rezervacijaPraonice>();
            this.sastanakSDoktorom = new HashSet<sastanakSDoktorom>();
            this.sastanakSDoktorom1 = new HashSet<sastanakSDoktorom>();
            this.vasIzborDana = new HashSet<vasIzborDana>();
        }
    
        public int id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public Nullable<int> sobaId { get; set; }
        public string korisnickoIme { get; set; }
        public string lozinka { get; set; }
        public int ulogaId { get; set; }
    
        public virtual soba soba { get; set; }
        public virtual uloga uloga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<korisnikLijeka> korisnikLijeka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nalaz> nalaz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<podsjetnik> podsjetnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rezervacijaPraonice> rezervacijaPraonice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sastanakSDoktorom> sastanakSDoktorom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sastanakSDoktorom> sastanakSDoktorom1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vasIzborDana> vasIzborDana { get; set; }
    }
}
