//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Class_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class lijekoviZaDijagnozu
    {
        public int id { get; set; }
        public int lijekId { get; set; }
        public int nalazId { get; set; }
    
        public virtual lijek lijek { get; set; }
        public virtual nalaz nalaz { get; set; }
    }
}
