//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Class_Library
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSDomEntities : DbContext
    {
        public MSDomEntities()
            : base("name=MSDomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<anketa> anketa { get; set; }
        public virtual DbSet<izbor> izbor { get; set; }
        public virtual DbSet<izborKategorija> izborKategorija { get; set; }
        public virtual DbSet<korisnik> korisnik { get; set; }
        public virtual DbSet<korisnikLijeka> korisnikLijeka { get; set; }
        public virtual DbSet<lijek> lijek { get; set; }
        public virtual DbSet<lijekoviZaDijagnozu> lijekoviZaDijagnozu { get; set; }
        public virtual DbSet<nalaz> nalaz { get; set; }
        public virtual DbSet<pitanje> pitanje { get; set; }
        public virtual DbSet<pitanjeSAnkete> pitanjeSAnkete { get; set; }
        public virtual DbSet<podsjetnik> podsjetnik { get; set; }
        public virtual DbSet<praonica> praonica { get; set; }
        public virtual DbSet<rezervacijaPraonice> rezervacijaPraonice { get; set; }
        public virtual DbSet<sastanakSDoktorom> sastanakSDoktorom { get; set; }
        public virtual DbSet<soba> soba { get; set; }
        public virtual DbSet<tipSobe> tipSobe { get; set; }
        public virtual DbSet<uloga> uloga { get; set; }
        public virtual DbSet<vasIzborDana> vasIzborDana { get; set; }
    }
}
