//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSDom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSDomEntities : DbContext
    {
        public MSDomEntities()
            : base("name=MSDomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<anketa> anketas { get; set; }
        public virtual DbSet<izbor> izbors { get; set; }
        public virtual DbSet<izborKategorija> izborKategorijas { get; set; }
        public virtual DbSet<korisnik> korisniks { get; set; }
        public virtual DbSet<korisnikLijeka> korisnikLijekas { get; set; }
        public virtual DbSet<lijek> lijeks { get; set; }
        public virtual DbSet<lijekoviZaDijagnozu> lijekoviZaDijagnozus { get; set; }
        public virtual DbSet<nalaz> nalazs { get; set; }
        public virtual DbSet<pitanje> pitanjes { get; set; }
        public virtual DbSet<pitanjeSAnkete> pitanjeSAnketes { get; set; }
        public virtual DbSet<podsjetnik> podsjetniks { get; set; }
        public virtual DbSet<praonica> praonicas { get; set; }
        public virtual DbSet<rezervacijaPraonice> rezervacijaPraonices { get; set; }
        public virtual DbSet<sastanakSDoktorom> sastanakSDoktoroms { get; set; }
        public virtual DbSet<soba> sobas { get; set; }
        public virtual DbSet<tipSobe> tipSobes { get; set; }
        public virtual DbSet<uloga> ulogas { get; set; }
        public virtual DbSet<vasIzborDana> vasIzborDanas { get; set; }
        public virtual DbSet<narudzbenica> narudzbenicas { get; set; }
        public virtual DbSet<stavkeNarudzbenice> stavkeNarudzbenices { get; set; }
    }
}
