//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSDom
{
    using System;
    using System.Collections.Generic;
    
    public partial class podsjetnik
    {
        public int id { get; set; }
        public int korisnikId { get; set; }
        public System.DateTime datumVrijeme { get; set; }
        public string razlog { get; set; }
    
        public virtual korisnik korisnik { get; set; }
    }
}
